services:
  backend:
    build:
      context: ./data_sources
      dockerfile: Dockerfile
    container_name: flask_backend
    volumes:
      - ./data_sources:/app
    environment:
      - FLASK_ENV=production
    ports: 
      - 5112:5000
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: "http://localhost:5112/api"
        SERVE_PORT: "5111"
    container_name: react_frontend
    ports:
      - "5111:5111"
    depends_on:
      - backend
    restart: unless-stopped
